---
name: Response to a Push on a branch other than Master
# yamllint disable-line rule:truthy
on:
  push:
    branches-ignore:
    - master
jobs:
  edge-docker-build:
    name: Edge Docker Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      id: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Check for CRLF endings
      id: crlf-lint
      uses: erclu/check-crlf@v1
    - name: Setup Python
      id: python-setup
      uses: actions/setup-python@v1
    - name: Lint Python
      id: python-lint
      uses: whynothugo/python-linting@master
    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v1
      with:
        strict: true
    - name: Prepare Environment
      id: prepare
      env:
        DOCKER_IMAGE: ${{ github.repository }}
        DOCKER_PLATFORMS: linux/amd64
        VERSION: edge
      run: |
        TAGS="--tag ${DOCKER_IMAGE,,}:${VERSION}"
        echo ::set-output name=docker_image::${DOCKER_IMAGE,,}
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=buildx_args::--platform ${DOCKER_PLATFORMS} \
          --build-arg VERSION=${VERSION} \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
          --build-arg VCS_REF=${GITHUB_SHA::8} \
          ${TAGS} --file ./Dockerfile ./
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3
    - name: Docker Layer Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Build Images
      run: |
        docker buildx build \
          --output "type=image,push=false" \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache" \
          ${{ steps.prepare.outputs.buildx_args }}
    - name: Docker Login
      if: success()
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    - name: Push Images
      if: success()
      run: |
        docker buildx build \
          --output "type=image,push=true" \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          ${{ steps.prepare.outputs.buildx_args }}
    - name: Clear
      run: |
        rm -f ${HOME}/.docker/config.json
